/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      xs: "300px",
      "web-hover": { raw: "(hover: hover)" },
      ...defaultTheme.screens,
    },
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        negative: "var(--color-negative)",
        positive: "var(--color-positive)",
        "primary-background": "var(--background-primary)",
        "sec-background": "var(--background-sec)",
        "primary-text": "var(--color-text-primary)",
        "secondary-text": "var(--color-text-secondary)",
        "hover-background": "var(--hover-background)",
      },
      animation: {
        fade: "fadeIn 1s ease-in",
        fadeHeight: "fadeHeight .5s linear",
        "fade-in": "fade-in 2s ease-in",
        "slide-up": "slide-up 2s ease-in",
        "slide-down": "slide-down 2s ease-in",
      },
      keyframes: (theme) => ({
        fadeIn: {
          "0%": {
            opacity: 0,
            // transform: 'translateY(40px)',
          },
          "100%": {
            opacity: 1,
            // transform: 'translateY(0)',
          },
        },
        fadeHeight: {
          "0%": {
            height: "0rem",
          },
          "100%": {
            height: "2rem",
          },
        },
        "slide-up": {
          "0%": { transform: "translateY(24px)", opacity: 0 },
          "100%": { transform: "translateY(0)", opacity: 1 },
        },
        "slide-down": {
          "0%": { transform: "translateY(-24px)", opacity: 0 },
          "100%": { transform: "translateY(0)", opacity: 1 },
        },
        "fade-in": {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        drop: {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(1.05)" },
        },
      }),
    },
    // Animation sequencing plugin options
    animationSequence: {
      // Utility will be generated using the [index + 1] of these delay values
      // sequence: ['0s', '.5s', '1s', '1.5s', '2s', '2.5s'],
      options: {
        delayMultiple: 0.25,
        maxSequences: 20,
        // Default animation duration for sequenced animations
        // can be overridden via animation-duration utilities generated by the plugin
        duration: "0.5s",
        // Default animation timing function for animations
        easing: "ease-in-out",
        // Default fill mode applied to animations
        fillMode: "both",
      },
    },
    backgroundColor: (theme) => ({
      ...theme("colors"),
    }),
  },
  plugins: [require("./plugins/animation-sequencing")],
};
